name: Build Klick

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build Sources
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macOS-latest
          - windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 15
        uses: actions/setup-java@v1
        with:
          distribution: 'adopt'
          java-version: '15'

      - name: Lint
        run: ./gradlew :spotlessCheck --stacktrace

      - name: Package
        run: ./gradlew :package --stacktrace

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Build Artifacts
          path: build/compose/binaries/main/
          retention-days: 7
